### ISSUE TITLE
扫码后CF报错了

### ISSUE THREAD

**Issue by wenyi2372** [ACGDatabase/ACGDB#1]
之前alist添加的存储无法访问
![image](https://github.com/user-attachments/assets/4d24ea9f-3b1a-4162-9aee-0fd25f3edf5c)
重新扫码后CF报错了
![image](https://github.com/user-attachments/assets/2144e2a0-e212-4b32-965d-0cdb0c0627d4)

**Comment by pirazcueyw** [comment]
我也一样。

**Comment by jiemo9527** [comment]
标记一下，等一手解密

**Comment by Sakura-Byte** [comment]
Please refer to https://www.voicehub.top/oauth/alipan
